### PR TITLE
Font-based row height

### LINKED ISSUE #3: The row height of the text is hard-coded
If using a font which is taller than `terminalio.FONT` the rows overlap because an assumed height is hard-coded.
A variant of the simpletext with a bigger font
```python
"""Display the microcontroller CPU temperature in C and F on a display."""
import microcontroller
from adafruit_simple_text_display import SimpleTextDisplay

from adafruit_bitmap_font import bitmap_font
FONT = bitmap_font.load_font("/fonts/LibreBodoniv2002-Bold-27.bdf")  # A bigger font

temperature_data = SimpleTextDisplay(title="Temperature Data!", title_scale=2, font=FONT)

while True:
    temperature_data[0].text = "Temperature: {:.2f} degrees C".format(
        microcontroller.cpu.temperature
    )
    temperature_data[1].text = "Temperature: {:.2f} degrees F".format(
        (microcontroller.cpu.temperature * (9 / 5) + 32)
    )
    temperature_data.show()
```

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
Add dynamic row heights based on font used. (Closes #3)
*The row heights are almost certainly different to the previous version. This may affect some deployed code.*

Deprecate `title_length`, ignore it for now. It is no longer needed with the update to `Adafruit_CircuitPython_Display_Text` removing `max_glyphs`.

Refactor the scaling so that the `text_scale` is not a multiple of the `title_scale`.

Correctly add multiple rows with the color-cycling effect. Previously all new rows had the same color.

Tested on Pynt with `7.0.0-alpha.5` and the following code, testing both fonts in different runs:
```python
import microcontroller
import terminalio
from adafruit_bitmap_font import bitmap_font
from adafruit_simple_text_display import SimpleTextDisplay

FONT = bitmap_font.load_font("/fonts/LibreBodoniv2002-Bold-27.bdf")  # A big font
FONT = terminalio.FONT  # A small font
temperature_data = SimpleTextDisplay(
    title="Temperature Data!", title_scale=1, font=FONT, text_scale=2
)

temperature_data[14].text = "Row 14"
temperature_data[13].text = "Row 13"
temperature_data[12].text = "Row 12"
temperature_data[11].text = "Row 11"
temperature_data[10].text = "Row 10"
temperature_data[9].text = "Row 9"
temperature_data[8].text = "Row 8"
temperature_data[7].text = "Row 7"
temperature_data[6].text = "Row 6"
temperature_data[5].text = "Row 5"
temperature_data[4].text = "Row 4"
temperature_data[3].text = "Row 3"
temperature_data[2].text = "Row 2"
temperature_data[1].text = "Row 1"
temperature_data[0].text = "Row 0"

while True:
    temperature_data[0].text = "Temperature: {:.2f} degrees C".format(
        microcontroller.cpu.temperature
    )
    temperature_data[1].text = "Temperature: {:.2f} degrees F".format(
        (microcontroller.cpu.temperature * (9 / 5) + 32)
    )
    temperature_data.show()
```

### CODE REVIEW

**Comment by lesamouraipourpre** [comment]
**If anyone has any deployed code and can check this against it, especially MacroPad related, that would be great**

**Review by FoamyGuy — APPROVED** [review]
These changes look good to me.

I tested the example code that @lesamouraipourpre provided on a PyPortal with CircuitPython 7.0.0-alpha.4 and confirmed the issue noted with colors repeating.

I also tested the simpletest example from this repo as well as the example provided in the MacroPad library docs for the `display_text()` function from the MacroPad library. All of these appear to be working as intended to me. 

I also tried using a few different custom fonts in the above examples and confirmed that this does fix the issue of text getting stacked on top of each other as shown in the picture from the issue linked at the top of this PR.

**Comment by lesamouraipourpre** [comment]
As far as I can tell from grepping the Learn Guides repo, the only learn guide that uses the `display_text()` method of `MacroPad` is
https://learn.adafruit.com/adafruit-macropad-rp2040/macropad-midi

**Comment by FoamyGuy** [comment]
I will try out the midi project tomorrow to ensure the UI still looks as expected with these changes.

**Comment by FoamyGuy** [comment]
I tested the Midi project today on MacroPad with `7.0.0-alpha.5`. When running the version from this PR it is nearly identical to running the currently released version of Simple_Text_Display. 

The one tiny difference that I noticed is there appears to be a few pixels of space between the title text row and the first "normal" text row in the currently released version. Maybe 3-4px or so. If we want to get this back we could add a few pixels to `_next_y` when setting it after creating the title text. I'm not sure if that space was intentional originally or not we can check with Kattni during the week. I don't really have a preference on it though either way seems fine to me.

**Comment by lesamouraipourpre** [comment]
I'm slightly paranoid because of the rumours on Discord of the contents of the new Adabox. I don't want this update to mess up any demo code that is planned.

**Comment by lesamouraipourpre** [comment]
Code tested on a 240x135 screen with `title_scale=1` and `text_scale=1`

Before PR
Title was given 18 pixels and text 13 pixels
IMG_20210727_075457__01
After PR *Apologies for the poor focus*
Title and text get 14 pixels as determined from font
IMG_20210727_082607__01

I'm happy for this to be merged. If it's felt that we need to add extra padding around the title that can be done in a follow-up PR.

**Pull request merged**
